# Generated by Django 5.2.12 on 2026-03-26 05:40

from django.db import migrations, models


def migrate_existing_statuses(apps, schema_editor):
    Task = apps.get_model('todo_app', 'Task')
    Task.objects.filter(status='pending').update(status='todo')
    Task.objects.filter(status='completed').update(status='done')


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.RunPython(migrate_existing_statuses, migrations.RunPython.noop),
    ]
