# Generated by Django 5.2.12 on 2026-03-26 06:04

from django.db import migrations, models


def populate_task_positions(apps, schema_editor):
    Task = apps.get_model("todo_app", "Task")

    for user_id, status in Task.objects.order_by("user_id", "status", "deadline", "-created_at").values_list("user_id", "status").distinct():
        tasks = Task.objects.filter(user_id=user_id, status=status).order_by("deadline", "-created_at", "pk")
        for index, task in enumerate(tasks, start=1):
            task.position = index
            task.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_options_task_priority_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'deadline', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_task_positions, migrations.RunPython.noop),
    ]
